; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -passes=sandbox-vectorizer -sbvec-passes=boup-vectorize,pack-reuse,accept-or-revert -mtriple=x86_64-- -mattr=+sse4.1 -sbvec-force-seeds=stores %s -S | FileCheck %s --check-prefix=VECTOR-SSE4

define void @simple_cost_test(ptr %ptr) {
; VECTOR-SSE4-LABEL: define void @simple_cost_test(
; VECTOR-SSE4-SAME: ptr [[PTR:%.*]]) #[[ATTR0:[0-9]+]] {
; VECTOR-SSE4-NEXT:    [[PTR0:%.*]] = getelementptr double, ptr [[PTR]], i32 0
; VECTOR-SSE4-NEXT:    [[VECL:%.*]] = load <2 x double>, ptr [[PTR0]], align 8, !sb [[META0:![0-9]+]]
; VECTOR-SSE4-NEXT:    store <2 x double> [[VECL]], ptr [[PTR0]], align 8, !sb [[META0]]
; VECTOR-SSE4-NEXT:    ret void
;
  %ptr0 = getelementptr double, ptr %ptr, i32 0
  %ptr1 = getelementptr double, ptr %ptr, i32 1
  %ld0 = load double, ptr %ptr0
  %ld1 = load double, ptr %ptr1
  store double %ld0, ptr %ptr0
  store double %ld1, ptr %ptr1
  ret void
}

define void @pack_cost_test_(ptr %ptr) {
; VECTOR-SSE4-LABEL: define void @pack_cost_test_(
; VECTOR-SSE4-SAME: ptr [[PTR:%.*]]) #[[ATTR0]] {
; VECTOR-SSE4-NEXT:    [[PTR0:%.*]] = getelementptr float, ptr [[PTR]], i32 0
; VECTOR-SSE4-NEXT:    [[PTR1:%.*]] = getelementptr float, ptr [[PTR]], i32 1
; VECTOR-SSE4-NEXT:    [[LD0:%.*]] = load float, ptr [[PTR0]], align 4
; VECTOR-SSE4-NEXT:    [[LD1:%.*]] = load float, ptr [[PTR1]], align 4
; VECTOR-SSE4-NEXT:    [[PACK4:%.*]] = insertelement <4 x float> poison, float [[LD0]], i64 0
; VECTOR-SSE4-NEXT:    [[PACK5:%.*]] = insertelement <4 x float> [[PACK4]], float [[LD1]], i64 1
; VECTOR-SSE4-NEXT:    [[PACK6:%.*]] = insertelement <4 x float> [[PACK5]], float [[LD0]], i64 2
; VECTOR-SSE4-NEXT:    [[PACK7:%.*]] = insertelement <4 x float> [[PACK6]], float [[LD1]], i64 3, !sb [[META1:![0-9]+]]
; VECTOR-SSE4-NEXT:    [[VEC:%.*]] = fmul <4 x float> [[PACK7]], [[PACK7]], !sb [[META1]]
; VECTOR-SSE4-NEXT:    store <4 x float> [[VEC]], ptr [[PTR0]], align 4, !sb [[META1]]
; VECTOR-SSE4-NEXT:    ret void
;
  %ptr0 = getelementptr float, ptr %ptr, i32 0
  %ptr1 = getelementptr float, ptr %ptr, i32 1
  %ptr2 = getelementptr float, ptr %ptr, i32 2
  %ptr3 = getelementptr float, ptr %ptr, i32 3
  %ld0 = load float, ptr %ptr0
  %ld1 = load float, ptr %ptr1
  %mul0 = fmul float %ld0, %ld0
  %mul1 = fmul float %ld1, %ld1
  %mul2 = fmul float %ld0, %ld0
  %mul3 = fmul float %ld1, %ld1
  store float %mul0, ptr %ptr0
  store float %mul1, ptr %ptr1
  store float %mul2, ptr %ptr2
  store float %mul3, ptr %ptr3
  ret void
}
;.
; VECTOR-SSE4: [[META0]] = !{!"region", i32 0}
; VECTOR-SSE4: [[META1]] = !{!"region", i32 1}
;.
