; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -passes=sandbox-vectorizer -sbvec-vec-reg-bits=512 -sbvec-cost-threshold=-9999 %s -S | FileCheck %s --check-prefix=VECTOR

define void @debug_info(ptr %ptr) {
; VECTOR-LABEL: define void @debug_info(
; VECTOR-SAME: ptr [[PTR:%.*]]) {
; VECTOR-NEXT:    [[PTR0:%.*]] = getelementptr float, ptr [[PTR]], i32 0
; VECTOR-NEXT:    [[VECL:%.*]] = load <2 x float>, ptr [[PTR0]], align 4, !dbg [[DBG1:![0-9]+]], !sb [[META8:![0-9]+]]
; VECTOR-NEXT:    store <2 x float> [[VECL]], ptr [[PTR0]], align 4, !dbg [[DBG9:![0-9]+]], !sb [[META8]]
; VECTOR-NEXT:    ret void
;
  %ptr0 = getelementptr float, ptr %ptr, i32 0
  %ptr1 = getelementptr float, ptr %ptr, i32 1
  %ld0 = load float, ptr %ptr0, !dbg !10
  %ld1 = load float, ptr %ptr1, !dbg !11
  store float %ld0, ptr %ptr0, !dbg !12
  store float %ld1, ptr %ptr1, !dbg !13
  ret void
}

!llvm.module.flags = !{!8}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !2)
!1 = distinct !DISubprogram(name: "name", line: 1, flags: DIFlagPrototyped, unit: !0, scopeLine: 1, file: !2, scope: !2, type: !3)
!2 = !DIFile(filename: "file.c", directory: "/some/dir")
!3 = !DISubroutineType(types: !4)
!4 = !{null}
!8 = !{i32 2, !"Debug Info Version", i32 3}
!9 = distinct !DILexicalBlock(line: 40, column: 0, file: !1, scope: !1)
!10 = !DILocation(line: 42, scope: !9)
!11 = !DILocation(line: 43, scope: !9)
!12 = !DILocation(line: 44, scope: !9)
!13 = !DILocation(line: 45, scope: !9)
;.
; VECTOR: [[DBG1]] = !DILocation(line: 42, scope: [[META2:![0-9]+]])
; VECTOR: [[META2]] = distinct !DILexicalBlock(scope: [[META3:![0-9]+]], file: [[META3]], line: 40)
; VECTOR: [[META3]] = distinct !DISubprogram(name: "name", scope: [[META4:![0-9]+]], file: [[META4]], line: 1, type: [[META5:![0-9]+]], scopeLine: 1, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: [[META7:![0-9]+]])
; VECTOR: [[META4]] = !DIFile(filename: "file.c", directory: {{.*}})
; VECTOR: [[META5]] = !DISubroutineType(types: [[META6:![0-9]+]])
; VECTOR: [[META6]] = !{null}
; VECTOR: [[META7]] = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: [[META4]], isOptimized: false, runtimeVersion: 0, emissionKind: NoDebug)
; VECTOR: [[META8]] = !{!"region", i32 0}
; VECTOR: [[DBG9]] = !DILocation(line: 44, scope: [[META2]])
;.
