; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 3
; RUN: opt -passes=sandbox-vectorizer -sbvec-vec-reg-bits=512 -sbvec-cost-threshold=-9999 %s -S | FileCheck %s --check-prefix=VECTOR
; RUN: opt -passes=sandbox-vectorizer -sbvec-vec-reg-bits=512 -sbvec-cost-threshold=99999 %s -S | FileCheck %s --check-prefix=SCALAR

define <2 x float> @shuffle(ptr noalias %ptr) {
;
; VECTOR-LABEL: define <2 x float> @shuffle(
; VECTOR-SAME: ptr noalias [[PTR:%.*]]) {
; VECTOR-NEXT:    [[VECLD:%.*]] = load <2 x float>, ptr [[PTR]], align 8
; VECTOR-NEXT:    [[SHUFF:%.*]] = shufflevector <2 x float> [[VECLD]], <2 x float> poison, <2 x i32> <i32 1, i32 0>
; VECTOR-NEXT:    ret <2 x float> [[SHUFF]]
;
; SCALAR-LABEL: define <2 x float> @shuffle(
; SCALAR-SAME: ptr noalias [[PTR:%.*]]) {
; SCALAR-NEXT:    [[VECLD:%.*]] = load <2 x float>, ptr [[PTR]], align 8
; SCALAR-NEXT:    [[SHUFF:%.*]] = shufflevector <2 x float> [[VECLD]], <2 x float> poison, <2 x i32> <i32 1, i32 0>
; SCALAR-NEXT:    ret <2 x float> [[SHUFF]]
;
  %vecld = load <2 x float>, ptr %ptr
  %shuff = shufflevector <2 x float> %vecld, <2 x float> poison, <2 x i32>  <i32 1, i32 0>
  ret <2 x float> %shuff
}
