; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -passes=sandbox-vectorizer -sbvec-vec-reg-bits=512 -sbvec-cost-threshold=-9999 %s -S | FileCheck %s --check-prefix=VECTOR
; RUN: opt -passes=sandbox-vectorizer -sbvec-vec-reg-bits=512 -sbvec-cost-threshold=99999 %s -S | FileCheck %s --check-prefix=SCALAR

define void @cast(ptr %ptr, float %float) {
; VECTOR-LABEL: define void @cast(
; VECTOR-SAME: ptr [[PTR:%.*]], float [[FLOAT:%.*]]) {
; VECTOR-NEXT:    [[ADRRCAST:%.*]] = addrspacecast ptr [[PTR]] to ptr addrspace(1)
; VECTOR-NEXT:    [[BITCAST:%.*]] = bitcast float [[FLOAT]] to i32
; VECTOR-NEXT:    ret void
;
; SCALAR-LABEL: define void @cast(
; SCALAR-SAME: ptr [[PTR:%.*]], float [[FLOAT:%.*]]) {
; SCALAR-NEXT:    [[ADRRCAST:%.*]] = addrspacecast ptr [[PTR]] to ptr addrspace(1)
; SCALAR-NEXT:    [[BITCAST:%.*]] = bitcast float [[FLOAT]] to i32
; SCALAR-NEXT:    ret void
;
  %adrrcast = addrspacecast ptr %ptr to ptr addrspace(1)
  %bitcast = bitcast float %float to i32
  ret void
}
