; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 3
; RUN: opt -passes=sandbox-vectorizer -sbvec-vec-reg-bits=512 -sbvec-cost-threshold=-9999 %s -S | FileCheck %s --check-prefix=VECTOR
; RUN: opt -passes=sandbox-vectorizer -sbvec-vec-reg-bits=512 -sbvec-cost-threshold=99999 %s -S | FileCheck %s --check-prefix=SCALAR

define void @scalar_only(ptr noalias %ptr, float %val) {
;
; VECTOR-LABEL: define void @scalar_only(
; VECTOR-SAME: ptr noalias [[PTR:%.*]], float [[VAL:%.*]]) {
; VECTOR-NEXT:    [[PACK:%.*]] = insertelement <2 x float> poison, float [[VAL]], i64 0
; VECTOR-NEXT:    [[PACK1:%.*]] = insertelement <2 x float> [[PACK]], float [[VAL]], i64 1
; VECTOR-NEXT:    [[PTR0:%.*]] = getelementptr float, ptr [[PTR]], i32 0
; VECTOR-NEXT:    [[VECL:%.*]] = load <2 x float>, ptr [[PTR0]], align 4
; VECTOR-NEXT:    [[VEC:%.*]] = fadd <2 x float> [[PACK1]], [[VECL]]
; VECTOR-NEXT:    store <2 x float> [[VEC]], ptr [[PTR0]], align 4
; VECTOR-NEXT:    ret void
;
; SCALAR-LABEL: define void @scalar_only(
; SCALAR-SAME: ptr noalias [[PTR:%.*]], float [[VAL:%.*]]) {
; SCALAR-NEXT:    [[PTR0:%.*]] = getelementptr float, ptr [[PTR]], i32 0
; SCALAR-NEXT:    [[PTR1:%.*]] = getelementptr float, ptr [[PTR]], i32 1
; SCALAR-NEXT:    [[LD0:%.*]] = load float, ptr [[PTR0]], align 4
; SCALAR-NEXT:    [[LD1:%.*]] = load float, ptr [[PTR1]], align 4
; SCALAR-NEXT:    [[ADD0:%.*]] = fadd float [[VAL]], [[LD0]]
; SCALAR-NEXT:    [[ADD1:%.*]] = fadd float [[VAL]], [[LD1]]
; SCALAR-NEXT:    store float [[ADD0]], ptr [[PTR0]], align 4
; SCALAR-NEXT:    store float [[ADD1]], ptr [[PTR1]], align 4
; SCALAR-NEXT:    ret void
;
  %ptr0 = getelementptr float, ptr %ptr, i32 0
  %ptr1 = getelementptr float, ptr %ptr, i32 1
  %ld0 = load float, ptr %ptr0
  %ld1 = load float, ptr %ptr1
  %add0 = fadd float %val, %ld0
  %add1 = fadd float %val, %ld1
  store float %add0, ptr %ptr0
  store float %add1, ptr %ptr1
  ret void
}
