; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -passes=sandbox-vectorizer -sbvec-vec-reg-bits=512 -sbvec-cost-threshold=-9999 %s -S | FileCheck %s

; Unpacking <1 x i8> %ld1 from vector (%ld0,%ld1) should have a <1 x i8> type,
; which requires a bitcast.
define <1 x i8> @unpack_type_should_match_use_type(ptr %ptr) {
; CHECK-LABEL: define <1 x i8> @unpack_type_should_match_use_type(
; CHECK-SAME: ptr [[PTR:%.*]]) {
; CHECK-NEXT:    [[GEP0:%.*]] = getelementptr i8, ptr [[PTR]], i32 0
; CHECK-NEXT:    [[VECL:%.*]] = load <2 x i8>, ptr [[GEP0]], align 1, !sb [[META0:![0-9]+]]
; CHECK-NEXT:    [[UNPACK:%.*]] = extractelement <2 x i8> [[VECL]], i64 1, !sb [[META0]]
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast i8 [[UNPACK]] to <1 x i8>, !sb [[META0]]
; CHECK-NEXT:    store <2 x i8> [[VECL]], ptr [[GEP0]], align 1, !sb [[META0]]
; CHECK-NEXT:    ret <1 x i8> [[TMP1]]
;
  %gep0 = getelementptr i8, ptr %ptr, i32 0
  %gep1 = getelementptr i8, ptr %ptr, i32 1
  %ld0 = load <1 x i8>, ptr %gep0
  %ld1 = load <1 x i8>, ptr %gep1
  store <1 x i8> %ld0, ptr %gep0
  store <1 x i8> %ld1, ptr %gep1
  ret <1 x i8> %ld1
}

define <1 x i8> @unpack_type_should_match_use_type_lane2(ptr %ptr) {
; CHECK-LABEL: define <1 x i8> @unpack_type_should_match_use_type_lane2(
; CHECK-SAME: ptr [[PTR:%.*]]) {
; CHECK-NEXT:    [[GEP0:%.*]] = getelementptr i8, ptr [[PTR]], i32 0
; CHECK-NEXT:    [[VECL:%.*]] = load <4 x i8>, ptr [[GEP0]], align 4, !sb [[META1:![0-9]+]]
; CHECK-NEXT:    [[UNPACK:%.*]] = extractelement <4 x i8> [[VECL]], i64 3, !sb [[META1]]
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast i8 [[UNPACK]] to <1 x i8>, !sb [[META1]]
; CHECK-NEXT:    store <4 x i8> [[VECL]], ptr [[GEP0]], align 4, !sb [[META1]]
; CHECK-NEXT:    ret <1 x i8> [[TMP1]]
;
  %gep0 = getelementptr i8, ptr %ptr, i32 0
  %gep1 = getelementptr i8, ptr %ptr, i32 3
  %ld0 = load <3 x i8>, ptr %gep0
  %ld1 = load <1 x i8>, ptr %gep1
  store <3 x i8> %ld0, ptr %gep0
  store <1 x i8> %ld1, ptr %gep1
  ret <1 x i8> %ld1
}
;.
; CHECK: [[META0]] = !{!"region", i32 0}
; CHECK: [[META1]] = !{!"region", i32 1}
;.
