; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 3
; RUN: opt -passes=sandbox-vectorizer -sbvec-vec-reg-bits=512 -sbvec-cost-threshold=-9999 %s -S | FileCheck %s --check-prefix=VECTOR
; RUN: opt -passes=sandbox-vectorizer -sbvec-vec-reg-bits=512 -sbvec-cost-threshold=99999 %s -S | FileCheck %s --check-prefix=SCALAR

@Foo = external global ptr

define void @slp_widen_with_inline_gep(ptr noalias %ptr, float %val) {
; VECTOR-LABEL: define void @slp_widen_with_inline_gep(
; VECTOR-SAME: ptr noalias [[PTR:%.*]], float [[VAL:%.*]]) {
; VECTOR-NEXT:    [[PTR0:%.*]] = getelementptr float, ptr [[PTR]], i32 0
; VECTOR-NEXT:    [[PTR1:%.*]] = getelementptr float, ptr [[PTR]], i32 1
; VECTOR-NEXT:    [[LD0:%.*]] = load float, ptr [[PTR0]], align 4
; VECTOR-NEXT:    [[LD1:%.*]] = load float, ptr [[PTR0]], align 4
; VECTOR-NEXT:    [[PACK:%.*]] = insertelement <2 x float> poison, float [[LD0]], i64 0
; VECTOR-NEXT:    [[PACK1:%.*]] = insertelement <2 x float> [[PACK]], float [[LD1]], i64 1
; VECTOR-NEXT:    store <2 x float> [[PACK1]], ptr @Foo, align 4
; VECTOR-NEXT:    ret void
;
; SCALAR-LABEL: define void @slp_widen_with_inline_gep(
; SCALAR-SAME: ptr noalias [[PTR:%.*]], float [[VAL:%.*]]) {
; SCALAR-NEXT:    [[PTR0:%.*]] = getelementptr float, ptr [[PTR]], i32 0
; SCALAR-NEXT:    [[PTR1:%.*]] = getelementptr float, ptr [[PTR]], i32 1
; SCALAR-NEXT:    [[LD0:%.*]] = load float, ptr [[PTR0]], align 4
; SCALAR-NEXT:    [[LD1:%.*]] = load float, ptr [[PTR0]], align 4
; SCALAR-NEXT:    store float [[LD0]], ptr @Foo, align 4
; SCALAR-NEXT:    store float [[LD1]], ptr getelementptr (float, ptr @Foo, i32 1), align 4
; SCALAR-NEXT:    ret void
;
  %ptr0 = getelementptr float, ptr %ptr, i32 0
  %ptr1 = getelementptr float, ptr %ptr, i32 1
  %ld0 = load float, ptr %ptr0
  %ld1 = load float, ptr %ptr0
  store float %ld0, ptr getelementptr (float, ptr @Foo, i32 0)
  store float %ld1, ptr getelementptr (float, ptr @Foo, i32 1)
  ret void
}
