; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -passes=sandbox-vectorizer -sbvec-vec-reg-bits=512 -sbvec-cost-threshold=-9999 %s -S | FileCheck %s
; RUN: opt -passes=sandbox-vectorizer -sbvec-vec-reg-bits=512 -sbvec-cost-threshold=-9999 -sbvec-disable-instr-op-seeds %s -S | FileCheck %s --check-prefix=DISABLE

define void @single_instr_seeds_add(ptr %ptr, i8 %v0, i8 %v1) {
; CHECK-LABEL: define void @single_instr_seeds_add(
; CHECK-SAME: ptr [[PTR:%.*]], i8 [[V0:%.*]], i8 [[V1:%.*]]) {
; CHECK-NEXT:    [[PACK2:%.*]] = insertelement <2 x i8> poison, i8 [[V1]], i64 0
; CHECK-NEXT:    [[PACK3:%.*]] = insertelement <2 x i8> [[PACK2]], i8 [[V1]], i64 1, !sb [[META0:![0-9]+]]
; CHECK-NEXT:    [[PACK:%.*]] = insertelement <2 x i8> poison, i8 [[V0]], i64 0
; CHECK-NEXT:    [[PACK1:%.*]] = insertelement <2 x i8> [[PACK]], i8 [[V0]], i64 1, !sb [[META0]]
; CHECK-NEXT:    [[GEP0:%.*]] = getelementptr i8, ptr [[PTR]], i32 0
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr i8, ptr [[PTR]], i32 1
; CHECK-NEXT:    [[VEC:%.*]] = sub <2 x i8> [[PACK1]], [[PACK3]], !sb [[META0]]
; CHECK-NEXT:    [[UNPACK4:%.*]] = extractelement <2 x i8> [[VEC]], i64 1, !sb [[META0]]
; CHECK-NEXT:    [[UNPACK:%.*]] = extractelement <2 x i8> [[VEC]], i64 0, !sb [[META0]]
; CHECK-NEXT:    [[ADD:%.*]] = add i8 [[UNPACK]], [[UNPACK4]]
; CHECK-NEXT:    ret void
;
; DISABLE-LABEL: define void @single_instr_seeds_add(
; DISABLE-SAME: ptr [[PTR:%.*]], i8 [[V0:%.*]], i8 [[V1:%.*]]) {
; DISABLE-NEXT:    [[GEP0:%.*]] = getelementptr i8, ptr [[PTR]], i32 0
; DISABLE-NEXT:    [[GEP1:%.*]] = getelementptr i8, ptr [[PTR]], i32 1
; DISABLE-NEXT:    [[SUB0:%.*]] = sub i8 [[V0]], [[V1]]
; DISABLE-NEXT:    [[SUB1:%.*]] = sub i8 [[V0]], [[V1]]
; DISABLE-NEXT:    [[ADD:%.*]] = add i8 [[SUB0]], [[SUB1]]
; DISABLE-NEXT:    ret void
;
  %gep0 = getelementptr i8, ptr %ptr, i32 0
  %gep1 = getelementptr i8, ptr %ptr, i32 1
  %sub0 = sub i8 %v0, %v1
  %sub1 = sub i8 %v0, %v1
  %add = add i8 %sub0, %sub1
  ret void
}
;.
; CHECK: [[META0]] = !{!"region", i32 0}
;.
