; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -passes=sandbox-vectorizer -sbvec-cost-threshold=-9999 -sbvec-vec-reg-bits=128 %s -S | FileCheck %s --check-prefix=VECTOR-128
; RUN: opt -passes=sandbox-vectorizer -sbvec-cost-threshold=-9999 -sbvec-vec-reg-bits=256 %s -S | FileCheck %s --check-prefix=VECTOR-256
; RUN: opt -passes=sandbox-vectorizer -sbvec-cost-threshold=-9999 -sbvec-vec-reg-bits=512 %s -S | FileCheck %s --check-prefix=VECTOR-512
; RUN: opt -passes=sandbox-vectorizer -sbvec-cost-threshold=99999 -sbvec-vec-reg-bits=512 %s -S | FileCheck %s --check-prefix=SCALAR

define void @slp_widen_override_max_vf(ptr %ptr) {
; VECTOR-128-LABEL: define void @slp_widen_override_max_vf
; VECTOR-128-SAME: (ptr [[PTR:%.*]]) {
; VECTOR-128-NEXT:    [[PTR0:%.*]] = getelementptr double, ptr [[PTR]], i32 0
; VECTOR-128-NEXT:    [[PTR2:%.*]] = getelementptr double, ptr [[PTR]], i32 2
; VECTOR-128-NEXT:    [[PTR4:%.*]] = getelementptr double, ptr [[PTR]], i32 4
; VECTOR-128-NEXT:    [[PTR6:%.*]] = getelementptr double, ptr [[PTR]], i32 6
; VECTOR-128-NEXT:    [[VECL:%.*]] = load <2 x double>, ptr [[PTR0]], align 8
; VECTOR-128-NEXT:    [[VECL1:%.*]] = load <2 x double>, ptr [[PTR2]], align 8
; VECTOR-128-NEXT:    [[VECL2:%.*]] = load <2 x double>, ptr [[PTR4]], align 8
; VECTOR-128-NEXT:    [[VECL3:%.*]] = load <2 x double>, ptr [[PTR6]], align 8
; VECTOR-128-NEXT:    store <2 x double> [[VECL]], ptr [[PTR0]], align 8
; VECTOR-128-NEXT:    store <2 x double> [[VECL1]], ptr [[PTR2]], align 8
; VECTOR-128-NEXT:    store <2 x double> [[VECL2]], ptr [[PTR4]], align 8
; VECTOR-128-NEXT:    store <2 x double> [[VECL3]], ptr [[PTR6]], align 8
; VECTOR-128-NEXT:    ret void
;
; VECTOR-256-LABEL: define void @slp_widen_override_max_vf
; VECTOR-256-SAME: (ptr [[PTR:%.*]]) {
; VECTOR-256-NEXT:    [[PTR0:%.*]] = getelementptr double, ptr [[PTR]], i32 0
; VECTOR-256-NEXT:    [[PTR4:%.*]] = getelementptr double, ptr [[PTR]], i32 4
; VECTOR-256-NEXT:    [[VECL:%.*]] = load <4 x double>, ptr [[PTR0]], align 8
; VECTOR-256-NEXT:    [[VECL1:%.*]] = load <4 x double>, ptr [[PTR4]], align 8
; VECTOR-256-NEXT:    store <4 x double> [[VECL]], ptr [[PTR0]], align 8
; VECTOR-256-NEXT:    store <4 x double> [[VECL1]], ptr [[PTR4]], align 8
; VECTOR-256-NEXT:    ret void
;
; VECTOR-512-LABEL: define void @slp_widen_override_max_vf
; VECTOR-512-SAME: (ptr [[PTR:%.*]]) {
; VECTOR-512-NEXT:    [[PTR0:%.*]] = getelementptr double, ptr [[PTR]], i32 0
; VECTOR-512-NEXT:    [[VECL:%.*]] = load <8 x double>, ptr [[PTR0]], align 8
; VECTOR-512-NEXT:    store <8 x double> [[VECL]], ptr [[PTR0]], align 8
; VECTOR-512-NEXT:    ret void
;
; SCALAR-LABEL: define void @slp_widen_override_max_vf
; SCALAR-SAME: (ptr [[PTR:%.*]]) {
; SCALAR-NEXT:    [[PTR0:%.*]] = getelementptr double, ptr [[PTR]], i32 0
; SCALAR-NEXT:    [[PTR1:%.*]] = getelementptr double, ptr [[PTR]], i32 1
; SCALAR-NEXT:    [[PTR2:%.*]] = getelementptr double, ptr [[PTR]], i32 2
; SCALAR-NEXT:    [[PTR3:%.*]] = getelementptr double, ptr [[PTR]], i32 3
; SCALAR-NEXT:    [[PTR4:%.*]] = getelementptr double, ptr [[PTR]], i32 4
; SCALAR-NEXT:    [[PTR5:%.*]] = getelementptr double, ptr [[PTR]], i32 5
; SCALAR-NEXT:    [[PTR6:%.*]] = getelementptr double, ptr [[PTR]], i32 6
; SCALAR-NEXT:    [[PTR7:%.*]] = getelementptr double, ptr [[PTR]], i32 7
; SCALAR-NEXT:    [[LD0:%.*]] = load double, ptr [[PTR0]], align 8
; SCALAR-NEXT:    [[LD1:%.*]] = load double, ptr [[PTR1]], align 8
; SCALAR-NEXT:    [[LD2:%.*]] = load double, ptr [[PTR2]], align 8
; SCALAR-NEXT:    [[LD3:%.*]] = load double, ptr [[PTR3]], align 8
; SCALAR-NEXT:    [[LD4:%.*]] = load double, ptr [[PTR4]], align 8
; SCALAR-NEXT:    [[LD5:%.*]] = load double, ptr [[PTR5]], align 8
; SCALAR-NEXT:    [[LD6:%.*]] = load double, ptr [[PTR6]], align 8
; SCALAR-NEXT:    [[LD7:%.*]] = load double, ptr [[PTR7]], align 8
; SCALAR-NEXT:    store double [[LD0]], ptr [[PTR0]], align 8
; SCALAR-NEXT:    store double [[LD1]], ptr [[PTR1]], align 8
; SCALAR-NEXT:    store double [[LD2]], ptr [[PTR2]], align 8
; SCALAR-NEXT:    store double [[LD3]], ptr [[PTR3]], align 8
; SCALAR-NEXT:    store double [[LD4]], ptr [[PTR4]], align 8
; SCALAR-NEXT:    store double [[LD5]], ptr [[PTR5]], align 8
; SCALAR-NEXT:    store double [[LD6]], ptr [[PTR6]], align 8
; SCALAR-NEXT:    store double [[LD7]], ptr [[PTR7]], align 8
; SCALAR-NEXT:    ret void
;
  %ptr0 = getelementptr double, ptr %ptr, i32 0
  %ptr1 = getelementptr double, ptr %ptr, i32 1
  %ptr2 = getelementptr double, ptr %ptr, i32 2
  %ptr3 = getelementptr double, ptr %ptr, i32 3
  %ptr4 = getelementptr double, ptr %ptr, i32 4
  %ptr5 = getelementptr double, ptr %ptr, i32 5
  %ptr6 = getelementptr double, ptr %ptr, i32 6
  %ptr7 = getelementptr double, ptr %ptr, i32 7
  %ld0 = load double, ptr %ptr0
  %ld1 = load double, ptr %ptr1
  %ld2 = load double, ptr %ptr2
  %ld3 = load double, ptr %ptr3
  %ld4 = load double, ptr %ptr4
  %ld5 = load double, ptr %ptr5
  %ld6 = load double, ptr %ptr6
  %ld7 = load double, ptr %ptr7
  store double %ld0, ptr %ptr0
  store double %ld1, ptr %ptr1
  store double %ld2, ptr %ptr2
  store double %ld3, ptr %ptr3
  store double %ld4, ptr %ptr4
  store double %ld5, ptr %ptr5
  store double %ld6, ptr %ptr6
  store double %ld7, ptr %ptr7
  ret void
}
