; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 3
; RUN: opt -passes=sandbox-vectorizer -sbvec-vec-reg-bits=512 -sbvec-cost-threshold=-9999 %s -sbvec-passes=vectorize-packs -S | FileCheck %s --check-prefix=VECTOR
; RUN: opt -passes=sandbox-vectorizer -sbvec-vec-reg-bits=512 -sbvec-cost-threshold=99999 %s -sbvec-passes=vectorize-packs -S | FileCheck %s --check-prefix=SCALAR

define void @vectorize_pack_simple(ptr %ptr, float %v) {
;
; VECTOR-LABEL: define void @vectorize_pack_simple(
; VECTOR-SAME: ptr [[PTR:%.*]], float [[V:%.*]]) {
; VECTOR-NEXT:    [[PTR0:%.*]] = getelementptr float, ptr [[PTR]], i32 0
; VECTOR-NEXT:    [[VECL:%.*]] = load <3 x float>, ptr [[PTR0]], align 4
; VECTOR-NEXT:    [[UNPACK3:%.*]] = shufflevector <3 x float> [[VECL]], <3 x float> poison, <2 x i32> <i32 1, i32 2>
; VECTOR-NEXT:    [[UNPACK2:%.*]] = extractelement <3 x float> [[VECL]], i64 0
; VECTOR-NEXT:    [[UNPACK1:%.*]] = shufflevector <3 x float> [[VECL]], <3 x float> poison, <2 x i32> <i32 1, i32 2>
; VECTOR-NEXT:    [[UNPACK:%.*]] = extractelement <3 x float> [[VECL]], i64 0
; VECTOR-NEXT:    [[INS0:%.*]] = insertelement <4 x float> poison, float [[UNPACK2]], i32 0
; VECTOR-NEXT:    [[EXTR0:%.*]] = extractelement <2 x float> [[UNPACK3]], i32 0
; VECTOR-NEXT:    [[INS1:%.*]] = insertelement <4 x float> [[INS0]], float [[EXTR0]], i32 1
; VECTOR-NEXT:    [[EXTR1:%.*]] = extractelement <2 x float> [[UNPACK3]], i32 1
; VECTOR-NEXT:    [[INS2:%.*]] = insertelement <4 x float> [[INS1]], float [[EXTR1]], i32 2
; VECTOR-NEXT:    [[INS3:%.*]] = insertelement <4 x float> [[INS2]], float [[V]], i32 3
; VECTOR-NEXT:    store <4 x float> [[INS3]], ptr [[PTR]], align 16
; VECTOR-NEXT:    ret void
;
; SCALAR-LABEL: define void @vectorize_pack_simple(
; SCALAR-SAME: ptr [[PTR:%.*]], float [[V:%.*]]) {
; SCALAR-NEXT:    [[PTR0:%.*]] = getelementptr float, ptr [[PTR]], i32 0
; SCALAR-NEXT:    [[PTR1:%.*]] = getelementptr float, ptr [[PTR]], i32 1
; SCALAR-NEXT:    [[LD0:%.*]] = load float, ptr [[PTR0]], align 4
; SCALAR-NEXT:    [[LD1:%.*]] = load <2 x float>, ptr [[PTR1]], align 8
; SCALAR-NEXT:    [[INS0:%.*]] = insertelement <4 x float> poison, float [[LD0]], i32 0
; SCALAR-NEXT:    [[EXTR0:%.*]] = extractelement <2 x float> [[LD1]], i32 0
; SCALAR-NEXT:    [[INS1:%.*]] = insertelement <4 x float> [[INS0]], float [[EXTR0]], i32 1
; SCALAR-NEXT:    [[EXTR1:%.*]] = extractelement <2 x float> [[LD1]], i32 1
; SCALAR-NEXT:    [[INS2:%.*]] = insertelement <4 x float> [[INS1]], float [[EXTR1]], i32 2
; SCALAR-NEXT:    [[INS3:%.*]] = insertelement <4 x float> [[INS2]], float [[V]], i32 3
; SCALAR-NEXT:    store <4 x float> [[INS3]], ptr [[PTR]], align 16
; SCALAR-NEXT:    ret void
;
  %ptr0 = getelementptr float, ptr %ptr, i32 0, !sb !0
  %ptr1 = getelementptr float, ptr %ptr, i32 1, !sb !0
  %ld0 = load float, ptr %ptr0, !sb !0
  %ld1 = load <2 x float>, ptr %ptr1, !sb !0

  %ins0 = insertelement <4 x float> poison, float %ld0, i32 0, !sb !0

  %extr0 = extractelement <2 x float> %ld1, i32 0, !sb !0
  %ins1 = insertelement <4 x float> %ins0, float %extr0, i32 1, !sb !0
  %extr1 = extractelement <2 x float> %ld1, i32 1, !sb !0
  %ins2 = insertelement <4 x float> %ins1, float %extr1, i32 2, !sb !0

  %ins3 = insertelement <4 x float> %ins2, float %v, i32 3, !sb !0

  store <4 x float> %ins3, ptr %ptr, !sb !0
  ret void
}

!0 = !{!"region", i32 0}
