; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 3
; RUN: opt -passes=sandbox-vectorizer -sbvec-vec-reg-bits=512 -sbvec-cost-threshold=-9999 %s -S | FileCheck %s --check-prefix=VECTOR
; RUN: opt -passes=sandbox-vectorizer -sbvec-vec-reg-bits=512 -sbvec-cost-threshold=99999 %s -S | FileCheck %s --check-prefix=SCALAR

define void @diamond(ptr noalias %ptr) {
;
; VECTOR-LABEL: define void @diamond(
; VECTOR-SAME: ptr noalias [[PTR:%.*]]) {
; VECTOR-NEXT:    [[PTR0:%.*]] = getelementptr float, ptr [[PTR]], i32 0
; VECTOR-NEXT:    [[VECL:%.*]] = load <2 x float>, ptr [[PTR0]], align 4
; VECTOR-NEXT:    [[VEC:%.*]] = fsub <2 x float> [[VECL]], [[VECL]]
; VECTOR-NEXT:    [[VEC2:%.*]] = fadd <2 x float> [[VECL]], [[VECL]]
; VECTOR-NEXT:    [[VEC3:%.*]] = fadd <2 x float> [[VEC]], [[VEC2]]
; VECTOR-NEXT:    store <2 x float> [[VEC3]], ptr [[PTR0]], align 4
; VECTOR-NEXT:    ret void
;
; SCALAR-LABEL: define void @diamond(
; SCALAR-SAME: ptr noalias [[PTR:%.*]]) {
; SCALAR-NEXT:    [[PTR0:%.*]] = getelementptr float, ptr [[PTR]], i32 0
; SCALAR-NEXT:    [[PTR1:%.*]] = getelementptr float, ptr [[PTR]], i32 1
; SCALAR-NEXT:    [[LD0:%.*]] = load float, ptr [[PTR0]], align 4
; SCALAR-NEXT:    [[LD1:%.*]] = load float, ptr [[PTR1]], align 4
; SCALAR-NEXT:    [[L0:%.*]] = fsub float [[LD0]], [[LD0]]
; SCALAR-NEXT:    [[L1:%.*]] = fsub float [[LD1]], [[LD1]]
; SCALAR-NEXT:    [[R0:%.*]] = fadd float [[LD0]], [[LD0]]
; SCALAR-NEXT:    [[R1:%.*]] = fadd float [[LD1]], [[LD1]]
; SCALAR-NEXT:    [[ADD0:%.*]] = fadd float [[L0]], [[R0]]
; SCALAR-NEXT:    [[ADD1:%.*]] = fadd float [[L1]], [[R1]]
; SCALAR-NEXT:    store float [[ADD0]], ptr [[PTR0]], align 4
; SCALAR-NEXT:    store float [[ADD1]], ptr [[PTR1]], align 4
; SCALAR-NEXT:    ret void
;
  %ptr0 = getelementptr float, ptr %ptr, i32 0
  %ptr1 = getelementptr float, ptr %ptr, i32 1

  %ld0 = load float, ptr %ptr0
  %ld1 = load float, ptr %ptr1

  %l0 = fsub float %ld0, %ld0
  %l1 = fsub float %ld1, %ld1

  %r0 = fadd float %ld0, %ld0
  %r1 = fadd float %ld1, %ld1

  %add0 = fadd float %l0, %r0
  %add1 = fadd float %l1, %r1
  store float %add0, ptr %ptr0
  store float %add1, ptr %ptr1
  ret void
}
